db:
  image: "postgres:9.3"

  ports:
    - "5432"

  volumes:
    - "~/dbmounthost/:/var/lib/postgresql/data:rw"

redis:
  image: redis

elasticsearch:
  build: docker/elasticsearch/
  ports:
    - 9200:9200
    - 9300:9300

web:
  build: .
  command: /bin/bash -l -c "bundle exec rails s -p 3000 -b '0.0.0.0'" 
  volumes:                                                                                                
    - .:/rails_centos_docker
  ports:
    - "3000:3000"
  links:
    - db  
    - redis
    - elasticsearch